# Generated by Django 5.2.3 on 2025-08-22 08:33

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_socialprofile_commsdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commsdocument',
            name='doc_type',
            field=models.CharField(choices=[('cv', 'CV'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='commsdocument',
            name='file',
            field=models.FileField(upload_to=api.models.comms_document_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
