# Generated by Django 5.2.3 on 2025-08-28 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_commsdocument_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-start_date'], name='api_project_start_d_757506_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title'], name='api_project_title_68b90c_idx'),
        ),
    ]
