# Generated by Django 5.2.3 on 2025-08-28 12:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_contact_email_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4)),
                ('messages', models.JSONField(default=list)),
                ('ip_address', models.GenericIPAddressField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('cv', 'CV/Resume'), ('cover_letter', 'Cover Letter'), ('certificate', 'Certificate'), ('project_doc', 'Project Documentation'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('extracted_text', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('personal_info', 'Personal Information'), ('experience', 'Work Experience'), ('education', 'Education'), ('skill', 'Skill'), ('project', 'Project'), ('certificate', 'Certificate'), ('achievement', 'Achievement')], max_length=20)),
                ('content', models.JSONField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-confidence_score'],
            },
        ),
        migrations.CreateModel(
            name='JobMatchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('match_score', models.FloatField()),
                ('strengths', models.JSONField(default=list)),
                ('gaps', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('contact_form_submissions', models.IntegerField(default=0)),
                ('project_views', models.IntegerField(default=0)),
                ('resume_downloads', models.IntegerField(default=0)),
                ('job_match_queries', models.IntegerField(default=0)),
                ('ai_chat_sessions', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='api_project_start_d_757506_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='api_project_title_68b90c_idx',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='api.document'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioanalytics',
            unique_together={('date',)},
        ),
    ]
