# Generated by Django 5.2.3 on 2025-08-28 14:39

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_aiconversation_document_extracteddata_jobmatchquery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('master_cv', 'Master CV/Resume'), ('cover_letter', 'Cover Letter Template'), ('certificate', 'Professional Certificate'), ('transcript', 'Academic Transcript'), ('portfolio', 'Portfolio Document'), ('recommendation', 'Letter of Recommendation'), ('project_doc', 'Project Documentation'), ('achievement', 'Achievement/Award Document'), ('other', 'Other Career Document')], max_length=20)),
                ('file', models.FileField(upload_to=api.models.career_document_path)),
                ('description', models.TextField(blank=True, help_text='Brief description of the document')),
                ('extracted_text', models.TextField(blank=True)),
                ('structured_data', models.JSONField(default=dict, help_text='Processed structured data from document')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Currently Processing'), ('completed', 'Processing Completed'), ('failed', 'Processing Failed')], default='pending', max_length=20)),
                ('processing_notes', models.TextField(blank=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Include in AI profile generation')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority for AI processing (1=highest)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Document',
                'verbose_name_plural': 'Career Documents',
                'ordering': ['priority', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Didier Imanirahami', max_length=200)),
                ('professional_title', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('professional_summary', models.TextField(blank=True, help_text='Executive summary for recruiters')),
                ('career_objective', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('work_experience', models.JSONField(default=list, help_text='Structured work experience data')),
                ('education_background', models.JSONField(default=list, help_text='Educational qualifications')),
                ('technical_skills', models.JSONField(default=dict, help_text='Technical skills with proficiency levels')),
                ('certifications', models.JSONField(default=list, help_text='Professional certifications')),
                ('achievements', models.JSONField(default=list, help_text='Quantified professional achievements')),
                ('projects_portfolio', models.JSONField(default=list, help_text='Detailed project information')),
                ('ai_persona_description', models.TextField(blank=True, help_text='How the AI should represent this professional profile')),
                ('target_roles', models.JSONField(default=list, help_text='Target job roles for AI optimization')),
                ('key_strengths', models.JSONField(default=list, help_text='Top professional strengths to highlight')),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated_from_documents', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Professional Profile',
                'verbose_name_plural': 'Professional Profiles',
            },
        ),
    ]
