name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/portfolio_backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install uv flake8
          uv sync
      - name: Lint
        run: uv run flake8 .
      - name: Test
        run: uv run coverage run manage.py test
      - name: Coverage report
        run: uv run coverage xml

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install
        run: npm ci
      - name: Typecheck
        run: npm run typecheck
      - name: Build
        run: npm run build
